production:
  google_universal:
    key: '***REMOVED***'
    domain: 'www.rebankme.com'
development:
  google_universal:
    key: '***REMOVED***'
    domain: 'localhost'
  console:
    garbage: true
test: