production:
  google_universal:
    key: <%= ENV["GOOGLE_ANALYTICS_KEY"] %>
    domain: <%= ENV["GOOGLE_ANALYTICS_DOMAIN"] %>
development:
  google_universal:
    key: <%= ENV["GOOGLE_ANALYTICS_KEY"] %>
    domain: 'localhost'
  console:
    garbage: true
test: