# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.host_name = 'app'

  config.vm.network :forwarded_port, guest: 80, host: 4567
  config.vm.network :forwarded_port, id: 'ssh', guest: 22, host: 2222
  # config.vm.define "web" do |web|

  config.vm.synced_folder "../", "/app"
  config.vm.synced_folder "./puppet", "/etc/puppet"
  # end

  config.vm.provider 'virtualbox' do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end


  config.vm.provision 'shell', path: 'provision.sh'


end
