# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # config.vm.box = "hashicorp/precise64"

  #with guest additions
  # config.vm.box = "bkersten/precise64"

  config.vm.box = "precise64_vb_4_3_12_utf8"
  config.vm.box_url = "https://s3.amazonaws.com/eyefodder-vagrant-boxes/precise64_vb_4_3_12_utf8.box"


  # config.vm.box = "precise64"
  # config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.host_name = 'rebankme'

  config.vm.network :forwarded_port, guest: 3000, host: 3001
  config.vm.network :forwarded_port, id: 'ssh', guest: 22, host: 2222
  # config.vm.define "web" do |web|

  # config.vm.synced_folder "../", "/app"
  config.vm.synced_folder "./puppet", "/etc/puppet"
  config.vm.synced_folder "../", "/app", type: "rsync", rsync__exclude: [".git/", "ops/*", "tmp/", "log/"]
  # end

  config.vm.provider 'virtualbox' do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.name = 'rebankme'
  end

  # FIRST-RUN PROVISIONING
   # config.vm.provision 'shell', path: 'set_locale.sh'
   config.vm.provision 'shell', path: 'provision_2.sh'

   config.vm.provision 'shell', path: 'init_rails_environment.sh', privileged: false

  # # EACH UP PROVISIONING
      config.vm.provision 'shell', path: 'start_app.sh', privileged: false, run: 'always'




end
